(define (sqrt x)
  (define (square x)
    (* x x))
  (define (average x y)
    (/ (+ x y) 2))
  (define (good-enough? guess)
    (< (abs (- (square guess) x)) 0.001))
  (define (improve guess)
    (average guess (/ x guess)))
  (define (sqr-iter guess)
    (if (good-enough? guess)
        guess
        (sqr-iter (improve guess))))
  (sqr-iter 1.0))
